### PR TITLE
Enumerable_Methods

### PR DESCRIPTION
**Pull request by Amalcxc**
the complete Enumerable Methods with all the requirements 
#my_each
#my_each_with_index.
#my_select.
#my_all? 
#my_any?
#my_none?
#my_count
#my_map
#my_inject
#my_inject
#my_inject, e.g. multiply_els()
#my_map method to take a proc instead.
#my_map method to take either a proc or a block.

### CODE REVIEW

**Review by cyonii — CHANGES_REQUESTED** [review]
# Status: Changes Required ♻️✍️

Hello @Amalcxc and @fernandorpm, you have shown a great effort in this project. I'll like to highlight your excellence in:
- Keeping your code clean 😎
- keeping your linters green 🟢

## To Improve
Great effort so far, but there are some major issues we need to address in order to get your project approved.
- [x] Endeavour to write meaningful and descriptive commit messages in the future, avoid single word commit messages like "file", "my_select", etc.
- [x] Lots of your enumerable methods have failed to pass the tests they have been run against, please take a look at this report below to understand what is expected of your enumerable methods. Look at the **Failed examples** section below and work on your methods.

### Failed examples:

> Please take a look at this great [documentation](https://ruby-doc.org/core-2.6.5/Enumerable.html) for the Ruby enumerable, it's ideal to use the test cases used in this doc to test your methods as you are going to be replicating the methods of this module.

- [x] `#my_each` returns an Enumerator if no block is given
- [x] `#my_each` when a block is given, and when self is an array, it returns the array itself after calling the given block once for each element in self
- [x] `#my_each` when a block is given, and when self is a range, it returns the range itself after calling the given block once for each element in self
- [x] `#my_each` when a block is given, and when self is a range, it behaves like `#each` calls the given block once for each element in self
- [x] `#my_each` when a block is given, and when self is a hash, it behaves like `#each` calls the given block once for each element in self
- [x] `#my_each_with_index` returns an enumerator if no block is given
- [x] `#my_each_with_index` when a block is given, and when self is an array, it returns the array itself after calling the given block once for each element in self
- [x] `#my_each_with_index` when a block is given, and when self is a range, it returns the range itself after calling the given block once for each element in self
- [x] `#my_each_with_index` when a block is given, and when self is a range, it behaves like `#each_with_index` calls the given block once for each element in self
- [x] `#my_each_with_index` when a block is given, and when self is a hash, it behaves like `#each_with_index` calls the given block once for each element in self
- [x] `#my_select` returns an array containing all elements of enum for which the given block returns a true value
- [x] `#my_select` returns an enumerator if no block is given
- [x] `#my_all?` returns false if the block returns false or nil
- [x] `#my_all?` when no block or argument is given, it returns true when none of the collection members are false or nil
- [x] `#my_all?` when no block or argument is given, it returns false when one of the collection members are false or nil
- [x] `#my_all?` when a class is passed as an argument, it returns true if all of the collection is a member of such class
- [x] `#my_all?` when a class is passed as an argument, it returns true if all of the collection is a member of such class
- [x] `#my_all?` when a class is passed as an argument, it returns false if any of the collection is not a member of such class
- [x] `#my_all?` when a Regex is passed as an argument, it returns true if all of the collection matches the Regex
- [x] `#my_all?` when a Regex is passed as an argument, it returns false if any of the collection does not match the Regex
- [x] `#my_all?` when a pattern other than Regex or a Class is given, it returns true if all of the collection matches the pattern
- [x] `#my_all?` when a pattern other than Regex or a Class is given, it returns false if any of the collection does not match the pattern
- [x] `#my_any?` returns false if the block ever returns a value false or nil
- [x] `#my_any?` when no block or argument is given, it returns true if at least one of the collection is not false or nil
- [x] `#my_any?` when no block or argument is given, it returns false if at least one of the collection is not true
- [x] `#my_any?` when a class is passed as an argument, it returns true if at least one of the collection is a member of such class
- [x] `#my_any?` when a class is passed as an argument, it returns true if at least one of the collection is a member of such class
- [x] `#my_any?` when a Regex is passed as an argument, it returns true if any of the collection matches the Regex
- [x] `#my_any?` when a Regex is passed as an argument, it returns false if none of the collection matches the Regex
- [x] `#my_any?` when a pattern other than Regex or a Class is given, it returns false if none of the collection matches the pattern
- [x] `#my_any?` when a pattern other than Regex or a Class is given, it returns true if any of the collection matches the pattern
- [x] `#my_none?` returns false if the block ever returns true for all elements
- [x] `#my_none?` when no block or argument is given, it returns true only if none of the collection members is true
- [x] `#my_none?` when no block or argument is given, it returns false only if one of the collection members is true
- [x] `#my_none?` when a class is passed as an argument, it returns true if none of the collection is a member of such class
- [x] `#my_none?` when a class is passed as an argument, it returns true if none of the collection is a member of such class
- [x] `#my_none?` when a class is passed as an argument, it returns false if any of the collection is a member of such class
- [x] `#my_none?` when a Regex is passed as an argument, it returns true if none of the collection matches the Regex
- [x] `#my_none?` when a Regex is passed as an argument, it returns false if any of the collection matches the Regex
- [x] `#my_none?` when a pattern other than Regex or a Class is given, it returns true only if none of the collection matches the pattern
- [x] `#my_none?` when a pattern other than Regex or a Class is given, it returns false only if one of the collection matches the pattern
- [x] `#my_count?` returns the number of items in enum through enumeration
- [x] `#my_count?` counts the number of elements yielding a true value if a block is given
- [x] `#my_map?` returns a new array with the results of running a given block once for every element in enum.
- [x] `#my_map?` returns a new array with the results of running a given block once for every element in enum.
- [x] `#my_map?` returns a new array with the results of running a given block once for every element in enum
- [x] `#my_map?` returns an Enumerator if no block is given
- [x] `#my_map?` accepts a proc as an argument and returns a new array with the results of running the proc once for every element in enum.
- [x] `#my_map?` executes only the proc when both a block and a proc are given and returns a new array with the results of running the proc once for every element in enum.
- [x] `#my_map?` does not mutate the original array
- [x] `#my_inject?` raises a "LocalJumpError" when no block or argument is given
- [x] `#my_inject?` searches for the longest word in an array of strings
- [x] `#my_inject?` does not mutate the original array
- [x] `#my_inject?` when a block is given without an initial value combines all elements of enum by applying a binary operation, specified by a block
- [x] `#my_inject?` when a block is given without an initial value combines all elements of enum by applying a binary operation, specified by a block
- [x] `#my_inject?` when a block is given with an initial value combines all elements of enum by applying a binary operation, specified by a block
- [x] `#my_inject?` when a symbol is specified without an initial value combines each element of the collection by applying the symbol as a named method:range
- [x] `#my_inject?` when a symbol is specified with an initial value combines each element of the collection by applying the symbol as a named method

Keep your heads high and stay motivated.
Happy coding

### You can find me on slack 👉 [CY Kalu](https://microverse-students.slack.com/team/U01494U96FR) if you need further assistance or clarification. I'm always available and will be glad to help.

**Review by cyonii — CHANGES_REQUESTED** [review]
# Status: Changes Required ♻️✍️

Hello Team, I'm so thrilled to see how much you have implemented the required changes 👏🎉. Stay motivated and keep up this energy.

## To Improve
You have almost completed this project, but there are very few defects you need to fix so that we can round this up. You have only 4 test cases you need to look at. Please review the **Failure report** below:

**Failed examples:**

- [x] `#my_each` when a block is given, when self is a hash, it should behave like `#each` and call the given block once for each element in self
- [x] `#my_each_with_index` when a block is given, when self is a hash, it should behave like `#each_with_index` and call the given block once for each element in self
- [x] `#my_map` executes only the proc when both a block and a proc are given and returns a new array with the results of running the proc once for every element in enum.
- [x] `#my_inject` raises a `LocalJumpError` when no block or argument is given

#### Happy coding 💡💻

> ### You can find me on slack 👉 [CY Kalu](https://microverse-students.slack.com/team/U01494U96FR) if you need further assistance or clarification. I'm always available and will be glad to help.

**Review by rukundoeric — CHANGES_REQUESTED** [review]
# Status: ♻️ CHANGES REQUIRED ♻️
_Great job guys so far 👏 💯 👍. However, there are few issues we need to address before we move on, please check the comments below._

- ### To Highlight
  - [x] The project is clean. 💯
  - [x] The project follows Git flow. 💯

- ### To Improve 
  - [x] [MANDATORY] #my_map executes only the proc when both a block and a proc are given and returns a new array with the results of running the proc once for every element in enum. In this case, your function is throwing an error.
  - [x] [MANDATORY] Make sure all files not related to the project are added to gitignore. for instanse, `test.rb`.

_Please make all the required changes before you submit another code review. If you have any problems or concerns, you can reach out to me on Slack: Rukundo Eric 🚀 . I wish you all the very best 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/), 
Slack: Rukundo Eric**

**Comment by fernandorpm** [comment]
## To the next reviewer
Our last code reviewer asked us to remove the `test.rb` file, which contained the test cases that we've been using for the project.
But if you notice, we have NOT updated the readme file, because once the project gets approved, we're going to resubmit the `test.rb` file, as it is crucial to the understanding of whoever comes across this code later on.

**Review by BrianSammit — APPROVED** [review]
STATUS:  APPROVED :green_circle: 
-----------
Hello, @fernandorpm @Amalcxc  you did an amazing job on this project. Your project is working perfectly :100: :1st_place_medal: 
To keep in mind:
- [x] Be careful with the Git Flow. You make all the project on the development branch. And the pull request must be From the feature branch to the development branch. [Here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59882084/) you have a reminder how to work with Git Flow. This time I'm gonna approve the project but you must've fixed this in the first review. 
------------
Reachme on SLACK if you have any question
@ Brian Sammit Cruz Rodriguez
HAPPY CODING!! AND GOOD LUCK WITH THE COMING PROJECTS :four_leaf_clover: :crossed_fingers:

**Pull request merged**
